version: '3.3'
services:
  backend:
    image: 592115514/project234-backend:latest
    ports: 
      - "8090:8080"
    volumes:
      - type: bind
        source: ./projectData
        target: /usr/share/nginx/assets
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8091:80"