version: '3.3'
services:
  backend:
    image: 592115514/project234-backend:latest
    ports: 
      - "8093:8080"
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8094:80"
    volumes:
      - type: bind
        source: ./data
        target: /data
    