<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testSuiteForLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b92476dd-86fe-4492-9a8f-8e82e3fb0a94</testSuiteGuid>
   <testCaseLink>
      <guid>ef0534b4-e902-423c-83c8-ae8e006bf34a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/testAdminLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1d8b21a7-ca8d-4d1b-8229-e67fbcd28a22</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/test data for testLogin</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1d8b21a7-ca8d-4d1b-8229-e67fbcd28a22</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>9579f84e-2a7e-43ce-8fd4-36251f9c75c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1d8b21a7-ca8d-4d1b-8229-e67fbcd28a22</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>673b5106-3442-485c-9acd-54adabe15e5c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
